name: CD

on:
    workflow_run:
        workflows: ['CI']
        types:
            - completed

jobs:
    # Adapted from: https://github.com/prettier/prettier-vscode/blob/main/.github/workflows/main.yml
    package:
        name: Package
        runs-on: ubuntu-latest
        # Only proceed with packaging if the CI workflow was successful.
        if: github.event.workflow_run.conclusion == 'success'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: 'Install Node.js'
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - name: Install Dependencies
              run: npm install

            - name: Generate VSIX (via VSCE)
              run: npx @vscode/vsce package

            - name: Set VSIX Name and Path in Output
              id: vsix-output
              run: |
                  echo "VSIX_PATH=$(find . -maxdepth 1 -type f -iname "*.vsix" | head -1)" >> $GITHUB_OUTPUT
                  echo "VSIX_NAME=$(basename $(find . -maxdepth 1 -type f -iname "*.vsix" | head -1))" >> $GITHUB_OUTPUT

            - name: Upload VSIX Artifact
              uses: actions/upload-artifact@v4
              with:
                  # prettier-ignore
                  path: ${{ steps.vsix-output.outputs.VSIX_PATH }}
                  name: ${{ steps.vsix-output.outputs.VSIX_NAME }}

        outputs:
            VSIX_PATH: ${{ steps.vsix-output.outputs.VSIX_PATH }}
            VSIX_NAME: ${{ steps.vsix-output.outputs.VSIX_NAME }}

    # Automatically create a release:
    # - If no tag is present, the release will be a prerelease with an automatically generated 'latest' tag.
    # - If a tag is present, the release will be a stable release with the tag name.
    # NOTE: In future, if CD encounters issues after the release step (for example, failing to publish),
    # it's possible to rollback the release: https://github.com/author/action-rollback
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs: package
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download VSIX Artifact
              uses: actions/download-artifact@v4
              with:
                  name: ${{ needs.package.outputs.VSIX_NAME }}
                  path: ${{ needs.package.outputs.VSIX_PATH }}

            - name: Automatic Release
              uses: dciborow/action-github-releases@v1.0.1
              # Only proceed if no tag is present.
              if: startsWith(github.ref, 'refs/tags/') != true
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  automatic_release_tag: latest
                  # If a tag is present, the release will be a stable release with the tag name.
                  prerelease: true
                  title: Development Build [${{ github.ref }}] [${{ github.sha }}]
                  files: |
                      LICENSE.txt
                      ${{ needs.package.outputs.VSIX_PATH }}/${{ needs.package.outputs.VSIX_NAME }}

            - name: Manual Release
              uses: ncipollo/release-action@v1
              # Only proceed if a tag is present.
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  artifacts: ${{ needs.package.outputs.VSIX_PATH }}/${{ needs.package.outputs.VSIX_NAME }}
                  # Tags ending in '-snapshot', '-alpha', '-beta', or '-rc' (release candidate) are considered prereleases.
                  prerelease: ${{ endsWith(github.ref, '-snapshot') || endsWith(github.ref, '-alpha') || endsWith(github.ref, '-beta') || endsWith(github.ref, '-rc') }}
